### ISSUE TITLE
umich_oidc_userinfo shortcode name documentation is different than code

### ISSUE THREAD

**Issue by nobleclem** [its-webhosting/umich-oidc-login#3]
The shortcode documented as `umich_oidc_userinfo` is implemented in code as `umich_oidc_user_info` in `includes/class-run.php#L250`.

**Comment by markmont** [comment]
This is already fixed in the source and will be included in the next release.  I have an untested alpha release of 1.2.0 I can send you now, the first beta release of 1.2.0 should be available next week, and I'm looking at around the release date of WordPress 6.3 for the public release (currently around August 8).

**Comment by markmont** [comment]
I apologize for letting this sit for so long!  A fix (feaa32d) for this problem is now available in a beta release, [version 1.2.0-beta1](https://github.com/its-webhosting/umich-oidc-login/releases/tag/v1.2.0-beta1).  To test this beta release, you will need to download the .zip file and use its contents to manually replace the `wp-content/plugins/umich-oidc-login` folder in your installation of WordPress.  If all goes well, I plan on releasing version 1.2.0 via the WordPress plugin directory in mid-September.

Please let me know if you discover any problems in the beta release.

**Comment by markmont** [comment]
[Version 1.2.0](https://github.com/its-webhosting/umich-oidc-login/releases/tag/v1.2.0), which contains the fix for this issue, has been released and [published in the WordPress plugin directory](https://wordpress.org/plugins/umich-oidc-login/).
